name: WorldGuard
main: WorldGuard\WorldGuard
api: [3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11]
version: 1.2.5
author: [Muqsit, edited by VMPE Development Team]
website: Not showing due to self leak information.
description: WorldGuard, ported from Bukkit to PocketMine (MCPE.)
commands:
  region:
    aliases: ["rg"]
    default: op
permissions:
  worldguard.create:
    default: op
  worldguard.modify:
    default: op
  worldguard.delete:
    default: op
